import type { Metadata } from "next";
import { PolicyPage } from "../_components/content";
import { createMetadata } from "@/lib/seo";

export const metadata: Metadata = createMetadata({ title: "Terms of service", description: "Terms governing access to the Talkform website, demo, importer, documentation, and related services.", path: "/terms" });

export default function TermsPage() {
  return <PolicyPage eyebrow="Legal" title="Terms of service" description="These terms describe permitted use, responsibilities, current service limitations, and how to contact Talkform." sections={[
    { title: "Agreement and service", content: <p>By accessing Talkform, you agree to these terms. Talkform currently provides a website, public-form importer, guided browser interview, structured answer review and export, documentation, and experimental developer surfaces. Features may change, be unavailable, or remain in preview. If you use a Talkform supplied by another organization, that organization may impose additional terms.</p> },
    { title: "Your responsibilities", content: <p>You must have the rights and permissions needed for form content and personal information you submit. Provide accurate notices and obtain consent required for your interview. Do not collect secrets or regulated information unless you have confirmed that the complete service and your own workflow are suitable for that purpose.</p> },
    { title: "Acceptable use", content: <p>Do not use Talkform to violate law or another person&apos;s rights; bypass authentication or access controls; probe or disrupt systems without authorization; distribute malware; impersonate others; scrape private content; generate abusive traffic; or make consequential decisions based on inferred voice traits. Do not use the importer to access private networks, restricted forms, or content you do not control.</p> },
    { title: "User content and output", content: <p>You retain rights you have in your content. You grant the permissions needed to process it to provide, secure, and support the service. Transcripts, extracted fields, and summaries can contain errors. Review and correct output before relying on it, especially for names, contact details, dates, amounts, eligibility, employment, health, legal, financial, or safety matters.</p> },
    { title: "Third-party services", content: <p>Talkform depends on third-party hosting, AI, browser, and network services. Their availability and terms can affect the product. Links and imported forms are controlled by third parties. Talkform does not endorse or assume responsibility for third-party content.</p> },
    { title: "Availability and changes", content: <p>We may modify, suspend, rate-limit, or discontinue features to improve or secure the service. We do not promise uninterrupted operation, permanent storage, or compatibility with every browser, form provider, or integration. Keep copies of exports you need and test workflows before production use.</p> },
    { title: "Disclaimers and liability", content: <p>The service is provided on an as-available basis to the extent permitted by law. Talkform disclaims implied warranties where legally allowed. To the extent permitted by law, Talkform is not liable for indirect, incidental, special, consequential, exemplary, or lost-profit damages arising from use of the service. Rights that cannot legally be waived remain unaffected.</p> },
    { title: "Termination and contact", content: <p>You may stop using the service at any time. We may restrict access for violation, abuse, security risk, legal requirements, or operational necessity. Questions about these terms can be sent to <a href="mailto:support@talkform.ai">support@talkform.ai</a>. Because the operator&apos;s public legal entity and mailing address have not yet been published, do not treat this page as a substitute for a negotiated enterprise agreement.</p> },
  ]} />;
}
