import type { Metadata } from "next";
import Link from "next/link";
import { PolicyPage } from "../_components/content";
import { createMetadata } from "@/lib/seo";

export const metadata: Metadata = createMetadata({
  title: "Privacy policy",
  description: "How Talkform handles account, form, ChatGPT app, interview, audio, transcript, structured answer, usage, and support information.",
  path: "/privacy",
});

export default function PrivacyPage() {
  return <PolicyPage eyebrow="Legal" title="Privacy policy" description="This notice explains what Talkform processes, why, how it is shared, and the choices available to you." sections={[
    { title: "Scope and roles", content: <><p>This policy covers information processed through the Talkform website, ChatGPT app, browser demo, importer, support channel, and related services. A customer that configures an interview may determine the purpose and questions; in that setting, the customer may be the controller or business and Talkform may process information on its behalf. Contact the form owner first when an interview was provided by another organization.</p><p>Questions about this notice can be sent to <a href="mailto:support@talkform.ai">support@talkform.ai</a>.</p></> },
    { title: "Information we process", content: <ul><li>Form configuration and public form content you ask us to import.</li><li>For the Talkform ChatGPT app, the bounded tool input needed to list or review a template or prepare a form draft. The endpoint returns that result to ChatGPT and does not retain the form draft, prompt, conversation, transcript, answers, or tool payload.</li><li>For ChatGPT app abuse prevention, a versioned HMAC-pseudonymized network-address bucket, a global bucket, minute window, request count, and expiry timestamp. Raw network addresses are not stored in this counter table.</li><li>For the public browser demo, Talkform receives the form configuration needed to issue a short-lived realtime token plus request-security information such as IP address, request timing, and error events.</li><li>OpenAI processes microphone audio and produces the live voice response, transcript, summary, and structured answer updates for voice mode.</li><li>Account, subscription, entitlement, and billing-status information when account or billing features are used. Talkform does not receive complete payment-card details from Stripe.</li><li>Messages and contact details you choose to send to support.</li></ul> },
    { title: "How we use information", content: <p>We use information to provide and secure the requested interview, validate and export answers, import a public form, troubleshoot failures, prevent abuse, communicate about support, comply with law, and improve the service using appropriately limited data. We do not use voice to infer protected traits, emotion, honesty, or suitability.</p> },
    { title: "Microphone, audio, and typed choice", content: <><p>Microphone access requires your browser permission and is requested only after you choose voice. When voice is enabled, Talkform issues a short-lived realtime token; your browser then streams audio directly to OpenAI. Talkform does not proxy that audio stream.</p><p>In the current public demo, transcript, summary, and structured answers remain in your browser until export and are not retained by the Talkform server. Typing stays in your browser until export and never requests microphone permission. A deployment may disable public voice entirely, in which case the demo remains text-only.</p><p>Do not share passwords, payment card numbers, government identifiers, health information, or other sensitive data unless the form owner has clearly requested it through an appropriate reviewed process.</p></> },
    { title: "Sharing and subprocessors", content: <p>We may disclose information to service providers that host the application, provide realtime AI processing, monitor security, or support operations, subject to appropriate terms. We may also disclose information when legally required, to protect rights and safety, or as part of a business transaction with applicable safeguards. See the <Link href="/subprocessors">subprocessor list</Link> for the current public summary.</p> },
    { title: "Retention and deletion", content: <><p>The Talkform ChatGPT app does not persist form drafts, prompts, conversations, transcripts, answers, or raw tool payloads. Its HMAC-pseudonymized abuse-prevention counters expire 15 minutes after their minute window; expired rows are deleted during later limiter activity. Because no submitted content is retained by this endpoint, there is no Talkform content record to retrieve or delete from it.</p><p>The public browser demo does not create a Talkform server session. Its transcript, summary, and structured answers remain browser-local until you export them, and leaving or refreshing the page clears that in-memory interview state.</p><p>Developer integrations that explicitly enable Talkform&apos;s process-local reference API have a different boundary: active records become inaccessible after 30 minutes, while completed or abandoned records become inaccessible within 10 minutes. Expired entries are purged on the next session API access or when the runtime is recycled, so this lazy, process-local cleanup is not a durable retention or deletion system. The store keeps minimized structured values but not transcript or summary copies.</p><p>Service-provider retention for information processed by OpenAI, Vercel, Clerk, Stripe, or Neon is governed by the applicable service terms and account configuration. The service is still maturing; customers should not collect regulated or highly sensitive data until a written retention and deletion configuration has been confirmed.</p></> },
    { title: "Choices and rights", content: <p>Depending on where you live, you may have rights to request access, correction, deletion, portability, restriction, or information about processing, and to object or withdraw consent. Email support@talkform.ai with the interview link, form owner, approximate date, and a safe way to verify your request. We may need to direct requests to the customer that controlled the interview.</p> },
    { title: "Security and international processing", content: <p>We use technical and organizational measures intended to protect information, but no Internet service is completely secure. Providers may process information in countries other than yours, subject to their terms and available transfer safeguards. Review our <Link href="/security">security page</Link> for current practices and limitations.</p> },
    { title: "Children and changes", content: <p>Talkform is not directed to children and should not be used to collect children&apos;s personal information without an appropriately reviewed consent and privacy process. We may update this notice as the product changes. We will revise the date above and provide additional notice when required.</p> },
  ]} />;
}
