import Link from "next/link";
import { redirect } from "next/navigation";
import { getOperatorUsage, requireOperator } from "@/lib/platform/operator";
import { PlatformError } from "@/lib/platform/types";
import { currentUser } from "@clerk/nextjs/server";
import { SwitchAccountButton } from "@/components/workspace-navigation";
import { getOperatorEmailDeliveryStatus } from "@/lib/operator-notifications/resend-transport";
import accountStyles from "@/components/workspace-navigation.module.css";
import styles from "../workspace.module.css";
export const dynamic = "force-dynamic";
export const metadata = { title: "Operator usage", robots: { index: false, follow: false } };
const usd = (value: number) => new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", minimumFractionDigits: 2, maximumFractionDigits: 4 }).format(value / 1_000_000);
export default async function UsagePage() {
  let userId: string;
  try { userId = await requireOperator(); } catch (error) {
    if (error instanceof PlatformError && error.status === 401) redirect("/sign-in?redirect_url=/dashboard/usage");
    if (!(error instanceof PlatformError) || error.status !== 403) throw error;
    const user = await currentUser();
    return <main className={accountStyles.access}><h1>This is the owner’s usage report</h1><p>Your account can manage its own projects. Site-wide usage and cost information is available only to the Talkform owner.</p>{user?.primaryEmailAddress?.emailAddress && <p>Signed in as <span className={accountStyles.identity}>{user.primaryEmailAddress.emailAddress}</span></p>}<div className={accountStyles.actions}><Link href="/dashboard">Go to your projects</Link><SwitchAccountButton label="Switch account" /></div></main>;
  }
  const data = await getOperatorUsage(userId);
  const emailDelivery = getOperatorEmailDeliveryStatus(process.env);
  const emailDeliveryStatus = emailDelivery.configured
    ? "Email sending is configured through Resend. Provider acceptance still does not prove inbox delivery."
    : `Unavailable: ${emailDelivery.reason ?? "resend_not_configured"}. Alerts remain recorded here until provider configuration is available.`;
  const pendingOwnerEmails = (data.notificationHealth.byStatus.pending ?? 0)
    + (data.notificationHealth.byStatus.retry ?? 0)
    + (data.notificationHealth.byStatus.delivering ?? 0);
  return <main className={styles.workspace}><div className={styles.intro}><span className={styles.eyebrow}>Talkform operator</span><h1>Are agents coming back?</h1><p>Last 30 days, UTC. Activation means a project retrieved a submitted result. Repeat use means retrievals on at least two different days. Funnel and retention counts exclude internal and test projects; the project table shows all projects with their environment.</p><Link href="/dashboard">Your workspace</Link> · <a href="/dashboard/usage">Refresh</a></div>
    <section className={styles.panel}><h2>Registrations</h2><div className={styles.stats}><div><strong>{data.registrations.machine.last_30_days}</strong><span>Agent workspaces, 30 days</span></div><div><strong>{data.registrations.machine.all_time}</strong><span>Agent workspaces, tracked total</span></div><div><strong>{data.registrations.human.last_30_days}</strong><span>Human signups, 30 days</span></div><div><strong>{data.registrations.clerk?.baselineTotal ?? "Unavailable"}</strong><span>Existing Clerk users at tracking start</span></div></div><p className={styles.muted}>Agent workspace counts come from committed autonomous registrations. Human signups come from Clerk’s user API after notification tracking began. Project creation is not counted as a human signup. Last sync: {data.registrations.clerk?.lastSuccessAt ? new Date(data.registrations.clerk.lastSuccessAt).toLocaleString("en-US", { timeZone: "UTC" }) + " UTC" : "Unavailable"}{data.registrations.clerk?.lastErrorCode ? `; latest sync error: ${data.registrations.clerk.lastErrorCode}` : ""}.</p></section>
    <section className={styles.panel}><h2>Integration funnel</h2><div className={styles.stats}>{Object.entries(data.summary).map(([label, value]) => <div key={label}><strong>{value}</strong><span>{label.replace(/([A-Z])/g, " $1")}</span></div>)}</div><p className={styles.muted}>Opened means a valid private link loaded its interview configuration; it does not prove a person viewed it. Retrieval confirms that Talkform served the JSON; it does not confirm what the receiving agent did next.</p></section>
    <section className={styles.panel}><h2>How integrations connect</h2><p className={styles.muted}>Last 30 days, external production projects. Each stage is counted once per handoff, using its first successful server route. Repeated polling is excluded. Older events remain unknown.</p><div style={{ overflowX: "auto" }}><table style={{ width: "100%", textAlign: "left", borderSpacing: "16px" }}><thead><tr><th>Event</th><th>Surface</th><th>Count</th></tr></thead><tbody>{data.surfaceCounts.map((row) => <tr key={`${row.event}:${row.surface}`}><td>{row.event.replace("handoff.", "")}</td><td>{row.surface}</td><td>{row.count}</td></tr>)}</tbody></table></div>{data.surfaceCounts.length === 0 && <p>No external production events yet.</p>}</section>
    <section className={styles.panel}><h2>Weekly use</h2><p className={styles.muted}>The last 12 completed weeks, UTC. Eligible projects existed before the end of that week. Returning use requires a retrieved result, so repeated empty polling does not count.</p><div style={{ overflowX: "auto" }}><table style={{ width: "100%", textAlign: "left", borderSpacing: "16px" }}><thead><tr><th>Week starting</th><th>Retrieving / eligible projects</th><th>Opened</th><th>Submitted</th><th>Retrieved</th></tr></thead><tbody>{data.weeklyExternalProjects.map((row) => <tr key={row.weekStart}><td>{row.weekStart}</td><td>{row.retrievingProjects} / {row.eligibleExternalProductionProjects}</td><td>{row.openedHandoffs}</td><td>{row.completedHandoffs}</td><td>{row.retrievedHandoffs}</td></tr>)}</tbody></table></div></section>
    <section className={styles.panel}><h2>Next-week retention</h2><p className={styles.muted}>Projects are grouped by the week they first retrieved a submitted result. A project is retained when it retrieves a new result the following week. Both weeks must be complete.</p><div style={{ overflowX: "auto" }}><table style={{ width: "100%", textAlign: "left", borderSpacing: "16px" }}><thead><tr><th>First retrieval week</th><th>Cohort projects</th><th>Retained / eligible projects</th></tr></thead><tbody>{data.completedWeekCohorts.map((row) => <tr key={row.cohortWeek}><td>{row.cohortWeek}</td><td>{row.cohortProjects}</td><td>{row.weekOneRetainedProjects} / {row.weekOneEligibleProjects}</td></tr>)}</tbody></table></div>{data.completedWeekCohorts.length === 0 && <p>No completed retention cohorts yet.</p>}</section>
    <section className={styles.panel}><h2>AI cost controls</h2><div className={styles.stats}><div><strong>{usd(data.cost.daily_provider_estimate)}</strong>Today’s provider usage estimate</div><div><strong>{usd(data.cost.daily_reserved_exposure)}</strong>Today’s charged or reserved exposure</div><div><strong>{usd(data.cost.monthly_reserved_exposure)}</strong>Month exposure / {usd(data.policy.monthlyLimitMicrousd)} limit</div></div><p>Daily reservation limit: {usd(data.policy.dailyLimitMicrousd)}. Active voice sessions: {data.cost.active_realtime}. Unresolved terminations: {data.cost.termination_unknown}.</p><p className={styles.muted}>Estimates use observed provider tokens and a rate card. They are not invoices. Reservations prevent new AI sessions when the shared budget is exhausted; text interviews continue.</p></section>
    <section className={styles.panel}><h2>Voice cost per retrieved result</h2><div className={styles.stats}><div><strong>{data.voiceCost.measuredResults} / {data.voiceCost.completedRetrievedResults}</strong><span>Results with complete measured usage</span></div><div><strong>{data.voiceCost.p50Microusd == null ? "Unavailable" : usd(data.voiceCost.p50Microusd)}</strong><span>Median measured estimate</span></div><div><strong>{data.voiceCost.p95Microusd == null ? "Unavailable" : usd(data.voiceCost.p95Microusd)}</strong><span>95th percentile estimate</span></div><div><strong>{usd(data.voiceCost.unresolvedExposureMicrousd)}</strong><span>Unresolved reserved exposure</span></div></div><p className={styles.muted}>Last 30 days of external production voice handoffs that were completed and retrieved. Percentiles appear only for results whose provider usage was completely observed and settled. {data.voiceCost.unmeasuredResults} result{data.voiceCost.unmeasuredResults === 1 ? " is" : "s are"} unmeasured. These estimates are not provider invoices.</p></section>
    <section className={styles.panel}><h2>Limits and notification delivery</h2><p role="status">{emailDeliveryStatus}</p><div className={styles.stats}><div><strong>{Object.values(data.costDenials).reduce((sum, count) => sum + count, 0)}</strong><span>AI admissions blocked, 30 days</span></div><div><strong>{data.capacityDenials.filter((row) => row.denial_reason === "global").reduce((sum, row) => sum + row.count, 0)}</strong><span>Shared capacity blocks, 30 days</span></div><div><strong>{pendingOwnerEmails}</strong><span>Owner emails pending or retrying</span></div><div><strong>{data.notificationHealth.byStatus.dead ?? 0}</strong><span>Owner emails needing attention</span></div></div><p className={styles.muted}>AI blocks include shared daily/monthly budgets and aggregated per-user or concurrency limits. Shared platform capacity covers hosted handoffs and agent registrations. Per-address denials remain visible in aggregate and do not trigger an email. Last email sent: {data.notificationHealth.lastSentAt ? new Date(data.notificationHealth.lastSentAt).toLocaleString("en-US", { timeZone: "UTC" }) + " UTC" : "None recorded"}. A sent provider message is not proof of inbox delivery.</p></section>
    <section className={styles.panel}><h2>Projects</h2><p className={styles.muted}>Showing up to {data.projectLimit} newest projects. Account IDs identify signed-in developers; autonomous agent workspaces have no account ID. Form answers and respondent identities are excluded. Project costs cover hosted voice sessions in the last 30 days plus older unresolved sessions; public demos and imports appear only in shared totals. Observed estimates and reserved exposure can overlap and should not be added together.</p><div style={{ overflowX: "auto" }}><table style={{ width: "100%", textAlign: "left", borderSpacing: "16px" }}><thead><tr><th>Project / account</th><th>Kind</th><th>Created</th><th>Opened</th><th>Submitted</th><th>Retrieved</th><th>Surfaces</th><th>Provider estimate</th><th>Reserved / unknown exposure</th><th>Active keys</th><th>Last API use</th></tr></thead><tbody>{data.projects.map((p) => <tr key={p.id}><td>{p.name}<small className={styles.muted} style={{ display: "block" }}>{p.account_id ?? "Autonomous agent workspace"}</small></td><td>{p.internal ? "internal" : `${p.owner_kind} · ${p.environment}`}</td><td>{p.created}</td><td>{p.opened}</td><td>{p.completed}</td><td>{p.retrieved}</td><td>{[...new Set(p.surfaceCounts.map((row) => row.surface))].join(", ") || "None"}</td><td>{usd(p.cost.observedProviderEstimateMicrousd)}</td><td>{usd(p.cost.reservedUnknownExposureMicrousd)}</td><td>{p.active_keys}</td><td>{p.last_used_at ? new Date(p.last_used_at).toLocaleDateString("en-US", { timeZone: "UTC" }) : "Never"}</td></tr>)}</tbody></table></div></section>
    <p className={styles.muted}>This report uses Talkform’s operational database. Updated {new Date(data.generatedAt).toLocaleString("en-US", { timeZone: "UTC" })} UTC.</p>
  </main>;
}
